version: '3.4'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=boulder_db
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      POSTGRES_USER: testdbuser
      POSTGRES_PASSWORD: testdbpass
      POSTGRES_HOST: db    
      POSTGRES_PORT: 5432
      POSTGRES_DB: testdb
    ports:
      - 6000:6000
    depends_on:
      - db



